services:
  hub:
    image: selenium/hub:4.32
  chrome:
    image: selenium/node-chrome:4.32
    shm_size: 2g
    deploy: 
      replicas: 1
    depends_on:
      - hub
    env_file: .env
  firefox:
    image: selenium/node-firefox:4.32
    shm_size: 2g
    deploy: 
      replicas: 0
    depends_on:
      - hub
    env_file: .env